version: '3'
services:
  db:
    image: 'postgres:alpine'
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_DB: 'supermarket'
    volumes:
      - db-data:/var/lib/postgresql/data/
      - ./db/schema.sql:/docker-entrypoint-initdb.d/1-schema.sql
      - ./db/data.sql:/docker-entrypoint-initdb.d/2-data.sql

  pgadmin:
    image: dpage/pgadmin4:4.22
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_LISTEN_PORT: 80
    ports:
      - '64374:80'
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - db

volumes:
  db-data:
  pgadmin-data:
